# Generated by Django 5.1.2 on 2025-05-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='links',
            field=models.TextField(null=True),
        ),
    ]
