# Generated by Django 5.1.2 on 2025-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_userpost_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.AlterField(
            model_name='userpost',
            name='links',
            field=models.TextField(default='', null=True),
        ),
    ]
