# Generated by Django 5.1.7 on 2025-06-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_album_albumimagefile_albumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core_app.album'),
            preserve_default=False,
        ),
    ]
