# Generated by Django 5.2.1 on 2025-06-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_imagefile_public_album_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='standart',
            field=models.BooleanField(default=False),
        ),
    ]
