# Generated by Django 5.2.1 on 2025-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_tag_standart'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='necessary',
            field=models.BooleanField(default=False),
        ),
    ]
