# Generated by Django 5.2.1 on 2025-06-16 07:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_album_necessary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150)),
                ('file', models.ImageField(upload_to='images/posts')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=4096)),
            ],
        ),
        migrations.RemoveField(
            model_name='albumimagefile',
            name='album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='watched_by',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='public',
            new_name='shown',
        ),
        migrations.RemoveField(
            model_name='album',
            name='author',
        ),
        migrations.RemoveField(
            model_name='album',
            name='necessary',
        ),
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='standart',
        ),
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 16, 7, 59, 34, 427034, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/album_previews'),
        ),
        migrations.AddField(
            model_name='album',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_app.tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, to='core_app.image'),
        ),
    ]
