# Generated by Django 5.2.1 on 2025-06-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_image_link_post_remove_albumimagefile_album_and_more'),
        ('user_app', '0012_verificationcode_profile_friendship_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts_authored', to='core_app.image'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core_app.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='posts_viewed', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='link',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.post'),
        ),
        migrations.DeleteModel(
            name='AlbumImageFile',
        ),
        migrations.DeleteModel(
            name='AlbumTheme',
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
