# Generated by Django 5.2.1 on 2025-06-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_post_author_post_images_post_likes_post_tags_and_more'),
        ('user_app', '0012_verificationcode_profile_friendship_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.profile'),
        ),
    ]
