# Generated by Django 5.1.2 on 2025-05-16 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_account_friends_alter_account_readers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='accounts_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='accounts_readers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='accounts_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
