# Generated by Django 5.2.1 on 2025-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_account_forbidden_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
