# Generated by Django 5.2.1 on 2025-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_account_password_account_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
