# Generated by Django 5.2.1 on 2025-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_account_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='none', upload_to='avatars/'),
        ),
    ]
