# Generated by Django 5.2.1 on 2025-06-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_app', '0001_initial'),
        ('user_app', '0012_verificationcode_profile_friendship_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_group', to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.chatgroup'),
        ),
    ]
